### ISSUE TITLE
NgOnInit ei ole vaja, kui seal sees midagi ei tee

### ISSUE THREAD

**Issue by SiimTa** [kertsiiner/movie-app#1]
https://github.com/kertsiiner/movie-app/blob/5f31ef83f4af8b73032788798c28a1f284f7b665/src/app/footer/footer.component.ts#L12

**Comment by kertsiiner** [comment]
https://github.com/kertsiiner/movie-app/commit/f0d261e18c97828c4ccc089290f74db2b7162080
