### ISSUE TITLE
Tühjad contstruktorid, ngOnInitid, scss

### ISSUE THREAD

**Issue by SiimTa** [kertsiiner/movie-app#11]
Ma ei viitsi ühte kommentaari igale poole panna. Põhimõtteliselt vaata üle, et ei ole mõttetuid asju, st mida ei kasutata tegelt. Praegu on silma jäänud scss failid, tühi ngOnInit lifecycle, tühi kontstruktor

https://github.com/kertsiiner/movie-app/blob/5f31ef83f4af8b73032788798c28a1f284f7b665/src/app/movie-list/components/movie-preview/movie-preview.component.ts#L12

**Comment by kertsiiner** [comment]
Täiesti nõus - puhas laiskus oli.
