### ISSUE TITLE
Tühi movie initial state

### ISSUE THREAD

**Issue by SiimTa** [kertsiiner/movie-app#13]
Seda ei tohiks küll vaja olla, st peab töötama nii, et seda ei ole vaja. Ütle, milles sul jama on, siis äkki saab vaadata miks nii on :) Ma arvan, et initial state ei ole üldse vaja, teine variant oleks:
```
const initialState: State = {
   movie: undefined
}
```
Aga see teeb sama välja

https://github.com/kertsiiner/movie-app/blob/5f31ef83f4af8b73032788798c28a1f284f7b665/src/app/movie-list/reducers/movie-details.reducer.ts#L15

**Comment by kertsiiner** [comment]
Nõus ja fixed
