### ISSUE TITLE
Siin peaks tegema 

### ISSUE THREAD

**Issue by SiimTa** [kertsiiner/movie-app#2]
https://github.com/kertsiiner/movie-app/blob/5f31ef83f4af8b73032788798c28a1f284f7b665/src/app/header/reducers/search.reducer.ts#L15

return {
   ...state,
   searchString: action.payload
};

St jätad vana state ka alles ja paned searchString juurde/muudad seda.

**Comment by kertsiiner** [comment]
Aga kui antud state koosnebki ainult searchStringist?

**Comment by SiimTa** [comment]
Best practice on ikkagi, et algupärane state on ka. Muidu lood dependency, et kui keegi midagi state lisab, siis peab seda switch blocki ka muutma

**Comment by kertsiiner** [comment]
Selge pilt
