### ISSUE TITLE
Tõsta Actionid, Effectid jne mujale

### ISSUE THREAD

**Issue by SiimTa** [kertsiiner/movie-app#7]
Eelistatakse üldjuhul UI ja SDK layeri eraldatust. 
St `https://github.com/kertsiiner/movie-app/tree/master/src/app` alla tee näiteks `/sdk/` folder ja sinna võid need feature based ikka panna.. St `movie-list/movie-list.action`, `movie-list/movie-list.effect` jne

**Comment by kertsiiner** [comment]
Done - nii tundub parem tõesti.
