### ISSUE TITLE
Uus selector

### ISSUE THREAD

**Issue by SiimTa** [kertsiiner/movie-app#8]
Ma teeks selle jaoks eraldi selectori.
getMovieById(id) ja siis kutsud seda hoopis siis :P

https://github.com/kertsiiner/movie-app/blob/5f31ef83f4af8b73032788798c28a1f284f7b665/src/app/movie-list/components/movie-details/movie-details.component.ts#L36

**Comment by kertsiiner** [comment]
Done - 'selectMovieById' selector
