### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by SiimTa** [kertsiiner/movie-app#9]
Angularis on tegelikult selline naming standard:
`movie` - Tavaline MovieModel
`movie$` - Observable
`movie$$` - Subscription
Lihtsalt nokkimise pärast :D
https://github.com/kertsiiner/movie-app/blob/5f31ef83f4af8b73032788798c28a1f284f7b665/src/app/movie-list/components/movie-details/movie-details.component.ts#L18

**Comment by kertsiiner** [comment]
Nüüd tean - peaks olema.
